Metrics/LineLength:
  Max: 160
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Exclude:
    - bin/*
    - Gemfile
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
  ExcludedMethods:
    - Gem::Specification.new
Naming/FileName:
  Exclude:
    - lib/a0-tzmigration-ruby.rb
