Metrics/LineLength:
  Max: 160
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Exclude:
    - bin/*
    - Gemfile
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
